spring:
  profiles:
    active:
      loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: d462629eb5351f
    password: 80f136e58f02d1
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true