spring:
  profiles:
    active:
      loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

      spring:
        mail:
          host: sandbox.smtp.mailtrap.io
          port: 2525
          username: 54e40d6000ac95
          password: 7bbd79c6bc3d10
          properties:
            mail:
              smtp:
                auth: true
                starttls.enable: true